# Generated by Django 5.0.6 on 2024-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('amenities', models.TextField()),
                ('images', models.ImageField(upload_to='accommodation_images')),
            ],
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='dining_images')),
                ('menu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='event_images')),
                ('ticket_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='heritage_images')),
            ],
        ),
        migrations.CreateModel(
            name='NatureActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='nature_images')),
            ],
        ),
    ]
