# Generated by Django 5.0.6 on 2024-07-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_amenity_remove_accommodation_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dining',
            name='images',
        ),
        migrations.CreateModel(
            name='DiningImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dining_images')),
                ('dining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.dining')),
            ],
        ),
    ]
