# Generated by Django 5.0.6 on 2024-07-17 10:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_dining_menu_dining_category_dining_dress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+966 503782355', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dining',
            name='dress',
            field=models.CharField(default='Smart casual', max_length=100),
        ),
    ]
