# Generated by Django 5.0.6 on 2024-07-18 07:07

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dining_phone_alter_dining_dress'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+966 503782355', max_length=128, region=None),
        ),
    ]
